-- Schema inicial (baseline). Gerado a partir das entidades com o dialeto do
-- PostgreSQL e revisado à mão. Mudança de schema daqui em diante é V2, V3...
-- nunca editar este arquivo depois de aplicado.

create table tarefas (
    id            bigint generated by default as identity primary key,
    titulo        varchar(120) not null,
    descricao     varchar(500),
    status        varchar(20)  not null check (status in ('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA')),
    prioridade    varchar(10)  not null check (prioridade in ('BAIXA', 'MEDIA', 'ALTA')),
    prazo         date,
    criada_em     timestamp(6) with time zone not null,
    atualizada_em timestamp(6) with time zone not null
);
